### ISSUE TITLE
Design files please

### ISSUE THREAD

**Issue by samuk** [MatthewJeffson/OSHW-WioTerminal#1]
This is not currently open source hardware by any accepted definition.

"The hardware must be released with documentation including design
files, and must allow modification and distribution of the design
files." https://www.oshwa.org/definition/

A cynic might think it's a case of https://openwashing.org/

**Comment by MatthewJeffson** [comment]
We usually share our open source design files in the "resources" section below our product wiki. As you can see in the [Wio Terminal](https://wiki.seeedstudio.com/Wio-Terminal-Getting-Started#resources), [reTerminal](https://matthewjeffson.github.io/custom/reTerminal#resources), [Seeed Studio XIAO](https://wiki.seeedstudio.com/xiao_esp32s3_getting_started#resources), etc...
We deeply apologize for the lack of clarity regarding our further open manufacturing thoughts. 

Thank you for your interests!
Have a good day!

**Comment by samuk** [comment]
In this case however you haven't shared the open source design files in the wiki. The Wiki links back to this Github page.

![OSHW](https://github.com/MatthewJeffson/OSHW-WioTerminal/assets/400875/bfdc79d3-55fa-4a18-96ea-b721a3971e32)

Until you share the Kicad/ Altium/ Eagle whatever files under a permissive licence you should not be describing it as Open Source Hardware.

This product does not meet the OSHW guidelines and you should not be using the OSHW logo: https://www.oshwa.org/open-source-hardware-logo/
